# Generated by Django 3.2.6 on 2021-10-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='domain_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
