# Generated by Django 3.2.6 on 2022-04-06 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wp_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wp_username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Admin'), (3, 'Super Admin')], default=1),
        ),
        migrations.AddField(
            model_name='store',
            name='wp_password',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='wp_username',
            field=models.CharField(default='tult', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='domain_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
