# Generated by Django 3.2.6 on 2021-08-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='templates.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('simple', 'simple'), ('grouped', 'grouped'), ('external', 'external'), ('variable', 'variable')], default='variable', max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('private', 'private'), ('publish', 'publish')], default='publish', max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('catalog_visibility', models.CharField(choices=[('visible', 'visible'), ('catalog', 'catalog'), ('search', 'search'), ('hidden', 'hidden')], default='visible', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('date_on_sale_from', models.DateField(null=True)),
                ('date_on_sale_to', models.DateField(null=True)),
                ('tax_status', models.CharField(choices=[('taxable', 'taxable'), ('shipping', 'shipping'), ('none', 'none')], default='taxable', max_length=255)),
                ('stock_quantity', models.IntegerField(default=1)),
                ('sold_individually', models.BooleanField(default=False)),
                ('tax_class', models.CharField(default='', max_length=255, null=True)),
                ('reviews_allowed', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(to='templates.Attribute')),
                ('categories', models.ManyToManyField(to='templates.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('tax_class', models.CharField(default='parent', max_length=255)),
                ('sale_price', models.FloatField()),
                ('regular_price', models.FloatField()),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='templates.template')),
            ],
        ),
        migrations.CreateModel(
            name='VariationAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.attribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.attributeoption')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='templates.variation')),
            ],
        ),
    ]
