# Generated by Django 3.2.6 on 2021-08-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='woo_id',
            field=models.IntegerField(),
        ),
    ]
