# Generated by Django 3.2.6 on 2022-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock_status',
            field=models.CharField(choices=[('instock', 'instock'), ('outofstock', 'outofstock')], default='instock', max_length=255),
        ),
    ]
