# Generated by Django 3.2.6 on 2021-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='attributes',
            field=models.ManyToManyField(to='templates.Attribute'),
        ),
    ]
