# Generated by Django 3.1.6 on 2021-09-04 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_category_woo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='template',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='template',
            name='sku',
        ),
        migrations.AddField(
            model_name='attribute',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='templates.template'),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='product_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
