# Generated by Django 3.1.6 on 2021-09-04 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_auto_20210904_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='templates.template'),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='product_title',
            field=models.CharField(max_length=255),
        ),
    ]
