# Generated by Django 3.2.6 on 2021-09-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_auto_20210904_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(max_length=255),
        ),
    ]
