# Generated by Django 3.2.6 on 2021-09-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_alter_variation_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeoption',
            old_name='code',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='template',
        ),
        migrations.RemoveField(
            model_name='attributeoption',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='attributeoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='product_title',
        ),
        migrations.AddField(
            model_name='template',
            name='attributes',
            field=models.ManyToManyField(to='templates.Attribute'),
        ),
        migrations.AddField(
            model_name='template',
            name='categories',
            field=models.ManyToManyField(to='templates.Category'),
        ),
        migrations.AddField(
            model_name='template',
            name='sku',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
