# Generated by Django 3.2.6 on 2021-09-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0009_auto_20210905_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeoption',
            old_name='option',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='template',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='template',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='template',
            name='sku',
        ),
        migrations.AddField(
            model_name='attribute',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrbiutes', to='templates.template'),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(max_length=255),
        ),
    ]
