# Generated by Django 3.1.6 on 2021-09-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0010_auto_20210905_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='templates.template'),
        ),
    ]
