# Generated by Django 3.1.6 on 2021-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_auto_20210911_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
