# Generated by Django 3.1.6 on 2021-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0013_auto_20210912_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='product_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
