# Generated by Django 3.1.6 on 2021-09-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0014_template_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
