# Generated by Django 3.1.6 on 2021-09-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0016_auto_20210916_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='id',
            new_name='uuid',
        ),
    ]
