# Generated by Django 3.2.6 on 2021-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_store_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Admin'), (3, 'Super Admin')], default=1),
        ),
    ]
