# Generated by Django 3.2.6 on 2021-12-26 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
