# Generated by Django 3.2.6 on 2022-03-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_store_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wp_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wp_username',
        ),
        migrations.AddField(
            model_name='store',
            name='wp_password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='wp_username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
